# DATA
data: /imagenet
img_size: 224
num_classes: 1000
channels_last: False

mean: null
std: null
crop_pct: null
interpolation: ''

no_aug: True
scale: [0.08, 1.0]
ratio: [0.75, 1.33]

hflip: 0.5
vflip: 0.
color_jitter: 0.4

aa: 'rand_m9_mstd0.5_inc1'
aug_splits: 0
jsd: False

reprob: False
remode: 'pixel'
recount: 1
resplit: False

mixup: 0.8
mixup_prob: 1.0
mixup_switch_prob: 0.5
mixup_mode: 'batch'
mixup_off_epoch: 0
cutmix: 1
cutmix_minmax: null

smoothing: 0.1
train_interpolation: 'random'

# ARCHITECTURE
model: 'soft_tiny'
pretrained: False 
initial_checkpoint: ''
gp: null
weight_decay: 0.05

# TRAINING
batch_size: 128
validation_batch_size_multiplier: 1

opt: 'adamw'
opt_eps: 1.e-8
opt_betas: null
sched: cosine

lr: 1.e-3
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
lr_cycle_mul: 1
lr_cycle_limit: 1
warmup_lr: 1.e-6
min_lr: 5.e-5
decay_epochs: 30
warmup_epochs: 10
cooldown_epochs: 10
patience_epochs: 10
decay_rate: 0.1
power: 1

momentum: 0.9
adam_epoch: 1000

clip_grad: 1.0

epochs: 300
start_epoch: null
resume: False
no_resume_opt: True
newton_maxiter: 20

drop: 0.0
drop_path: 0.1
drop_connect: null
drop_block: null
reset_drop: False

sync_bn: False
dist_bn: ''
split_bn: False
bn_tf: False
bn_momentum: null
bn_eps: null

model_ema: True
model_ema_force_cpu: False
model_ema_decay: 0.99996

amp: False
apex_amp: False
native_amp: False

# TESTING
eval: False
eval_checkpoint: '/home/mdb9823/bayesian_attention/SOFT/SOFT_Tiny.pth.tar'
recovery_interval: 0
eval_metric: 'top1'
tta: 0

# MISC
seed: 42
log_interval: 50
workers: 8
num_gpu: 1
save_images: False
pin_mem: False
no_prefetcher: False
output: ''
local_rank: 0
use_multi_epochs_loader: False